import { Page } from "../components/Page";
import {
  ChapterOpen,
  Cols,
  P,
  Lede,
  H2,
  M,
  Note,
  Figure,
  Spacer,
} from "../components/Blocks";

const SECTION = "05 · Terminal UI";

function Shot({ src, alt }: { src: string; alt: string }) {
  return <img src={src} alt={alt} style={{ display: "block", width: "100%" }} />;
}

export const ch5Pages = [
  <Page section={SECTION} key="ch5-1">
    <ChapterOpen index="05" title="An instrument panel for crashes" kicker="entropy-tui" />
    <Cols
      main={
        <>
          <Lede>
            A sweep of two hundred seeds prints two hundred JSONL lines, which
            is the right format for CI and the wrong one for a person.{" "}
            <M>entropy-tui</M> is the terminal front end that turns the
            simulator&apos;s output into something an operator can watch: a
            crash-recovery dashboard and a SQL console, drawn with FTXUI over
            the same stable JSONL schema the CLI emits.
          </Lede>
          <H2 n="5.1">Reproducible pixels</H2>
          <P>
            The interface animates in a terminal, and a PDF cannot; the frames
            on these pages are single stills of a moving surface. They are also
            reproducible artifacts in their own right: the binary&apos;s{" "}
            <M>--capture-frame</M> mode renders one named screen at a fixed
            size from the bundled demo dataset and writes the ANSI to stdout,
            so every image here can be regenerated byte for byte from the
            repository. CI builds the TUI on every push alongside the engine,
            so the panel cannot silently rot against the code it visualizes.
          </P>
        </>
      }
      rail={
        <>
          <Spacer h={148} />
          <Note label="three screens">
            Boot menu, crash-simulator dashboard, query console. The boot
            mark is a braille dot-matrix galaxy, animated in the live UI.
          </Note>
        </>
      }
    />
    <Figure
      n="5.1"
      pad={false}
      caption={<>The boot screen at rest. In the terminal the galaxy rotates; the menu keys drop into the dashboard, the console, and a recovery report.</>}
    >
      <Shot src="./tui/boot-trim.png" alt="Entropy TUI boot screen: braille galaxy mark, wordmark, and menu" />
    </Figure>
  </Page>,

  <Page section={SECTION} key="ch5-2">
    <Figure
      n="5.2"
      pad={false}
      caption={<>The dashboard mid-sweep. Every widget is a projection of the JSONL fields: the seed matrix buckets outcomes per schedule, the timeline plots per-run recovery_ms with p99 called out, and the fault feed streams each failing seed's invariant verdicts. The red band is deliberate: the bundled demo dataset replays the pre-fix torn-page sweep from chapter 02, 72 seeds failing committed_present.</>}
      style={{ marginTop: 0 }}
    >
      <Shot src="./tui/dashboard-trim.png" alt="Crash-recovery dashboard: KPIs, recovery sweep, invariant/seed matrix, run table, fault feed" />
    </Figure>
    <Figure
      n="5.3"
      pad={false}
      caption={<>The query console is not a mock: it embeds a live entropy::Database, loads the sweep's runs and schedules as tables, and every query on this screen runs through the engine's own parser, planner, and executors. The database answers questions about its own crash record.</>}
    >
      <Shot src="./tui/console-trim.png" alt="Query console: schema tree, SQL editor, and results grid over the runs table" />
    </Figure>
  </Page>,
];
